name: Arduino Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install Arduino cores
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:mbed_nano

    - name: Install Arduino libraries from libraries.txt
      run: |
        if [ -f libraries.txt ]; then
          while IFS= read -r lib; do
            arduino-cli lib install "$lib"
          done < libraries.txt
        else
          echo "libraries.txt not found!"
          exit 1
        fi

    - name: Compile all Arduino sketches
      run: |
        for sketch in $(find . -name "*.ino"); do
          arduino-cli compile --fqbn arduino:mbed_nano:nanorp2040connect "$sketch"
        done
