name: Arduino Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install Arduino cores and libraries
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:mbed_rp2040
        arduino-cli lib install Arduino_LSM6DSOX WiFiNINA

    - name: Compile all Arduino sketches
      run: |
        for sketch in $(find . -name "*.ino"); do
          arduino-cli compile --fqbn arduino:mbed_rp2040:rp2040 "$sketch"
        done
